### ISSUE TITLE
CSS Exercise 2

### ISSUE THREAD

**Issue by wilsonokibe** [wilsonokibe/CSS#1]
Create a CSS layout using div(do not use tables).Layout design is here:http://dl.dropbox.com/u/17934144/vtapp/exercise2.jpgIf you want to use background image for sidebar, here is the link for the same:http://dl.dropbox.com/u/17934144/vtapp/exercise2-bg.gif

https://github.com/wilsonokibe/CSS.git

**Comment by segunadeleye** [comment]
1. I can see a lot of repetitions in your code. Try to implement without repeating styles. There are different ways of doing this. multiple selection, classes are some of the ways of doing this.
2. Why do you need `color: black`? Doesn't the browser already handle that?;
3. Use HTML5 tags instead of using only `<div>`. Only use `<div>` where there are no alternative HTML5 tags.
4. You are expected to use box-sizing. We can discuss this once if you have any doubts.
5. Use proper tags for the headers (one of `h1`...`h6`)...Don't use `<strong>`
6. Why do you have two `padding-bottom` styling for `#nav` and `#section`.
7. There is an alternative to declaring "padding" attributes for each side.
8. There is still a difference in the heights of both sections. Using `padding-bottom: 400px` doesn't fix that. Try using the background image.

**Comment by wilsonokibe** [comment]
1. Repetition minimized
2. color: black, which is default for browser removed
3. Using HTML5 tags
4. Using Box-sizing
5. Using proper tags for headers
6. Padding-bottom removed
7. alternative padding delcaration used (shortcut)
8. Using backgroung image to correct column heights

**Comment by segunadeleye** [comment]
Looks okay. I am closing this for now.

However, we will need to discuss how to select and style element so as to avoid using unnecessary styles.
